# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8183506cf5086d04573f512058c558ded9d395d3035bfc8f3cf6da827f98eda3bf5e74c2c21437a8651ad97bef676723735335237ba5123d5fd67a42fe0fe6e

test:
  secret_key_base: 23725db36d02dd94dc8e89331926514da23609e0ff9575d9211dc27979d4eba3010d5893d7f3f03993db5c7372d1d7e31323c9428e2fa78e588a3b8c12893872

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
